version: '3'

services:
  db:
     image: postgres:9.6
     env_file: .env
     networks:
       - insomnia-network

  redis:
    image: redis:3.2.11-alpine
    networks:
      - insomnia-network

  api:
    build:
      context: ../../insomnia-api
      dockerfile: ./Dockerfile
    env_file: .env
    volumes:
      - ../../insomnia-api/www:/var/www
    depends_on:
      - redis
      - db
    ports:
      - 8080:80
    networks:
      - insomnia-network
    entrypoint: /var/start.sh

networks:
  insomnia-network: {}